### ISSUE TITLE
Add a recipe about dataset feature and MinIO integration

### ISSUE THREAD

**Issue by aoelvp94** [astronomer/2.4-example-dags#10]
Hi there 👋🏻 

I want to share with you the following recipe that we developed at [Mutt Data](https://github.com/MuttData) in order to contribute in this repo 🙂 You can check by yourself if you want, we want to upload this example in a properly way in this repo.

## MWE to play with Dataset feature

0. Install Astro CLI https://github.com/astronomer/astro-cli
1. Create a project in a test folder
``` bash
mkdir airflow-dataset-poc && cd airflow-dataset-poc
astro dev init
```

This generates a basic project directory:
```
.
├── dags
│   ├── example_dag_advanced.py
│   ├── example_dag_basic.py
├── tests
│   ├── dags
│       ├── test_dag_integrity.py
├── Dockerfile
├── include
├── packages.txt
├── plugins
└── requirements.txt
```

DAGs can go in the `dags` folder, custom Airflow plugins in `plugins`, python packages needed can go in `requirements.txt`, and OS level packages can go in `packages.txt`.

2. Run `astro dev start` to start a local version of airflow on your machine. This will spin up a few locally running docker containers - one for the airflow scheduler, one for the webserver, and one for postgres. (Run `astro dev ps` to verify).

3. Add minio to treat buckets/data in buckets as Airflow Dataset. Stop or kill the astro services. Let's re-create a new `docker-compose.override.yaml` file:

```yaml
version: '3'
services:

  minio-service:
    image: minio/minio
    container_name: minio-container
    command: server /data --console-address ":9001"
    ports: 
      - '9000:9000'
      - '9001:9001'
    volumes: 
      - ./minio:/data
    environment:
      - "MINIO_ROOT_USER=minio"
      - "MINIO_ROOT_PASSWORD=minio123"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  
  mc-service:
    image: minio/mc
    depends_on:
      minio-service:
        condition: service_healthy
    restart: on-failure
    volumes: 
      - ./data:/data
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio-container:9000 minio minio123;
      /usr/bin/mc mb myminio/mybucket;
      /usr/bin/mc policy set public myminio/mybucket;
      /usr/bin/mc mirror data/ myminio/mybucket;
      "

volumes:
  minio:

```

Also, add the following `requirements.txt` in the root project:
```
minio
```

4.  Copy the `wildfires.csv` file located in `resources/data` (here it is attached - [wildfires.csv](https://github.com/astronomer/2-4-example-dags/files/10114336/wildfires.csv)) in a new `data` folder. 

5. Copy the minio producer and consumer DAGs in `dags` folder and copy them into `dags` folder. 

`minio_producer_dag.py`:
```python
from minio import Minio
import pandas as pd
import numpy as np
from io import BytesIO
from datetime import timedelta

from airflow import Dataset
from airflow.decorators import dag, task
from airflow.utils.dates import days_ago


MINIO_ENDPOINT = "host.docker.internal:9000"
ACCESS_KEY = "minio"
SECRET_KEY = "minio123"
BUCKET_NAME = "mybucket"
CSV_FILENAME = "wildfires.csv"

@dag(
    "minio_producer",
    schedule=timedelta(days=1),
    start_date=days_ago(2),
    tags=["dataset"],
)
def dag_decorator():
    @task
    def extract() -> pd.DataFrame:
        client = Minio(MINIO_ENDPOINT, access_key=ACCESS_KEY, secret_key=SECRET_KEY, secure=False)
        print("Going to read the data in Minio..")
        df = pd.read_csv(client.get_object(BUCKET_NAME, CSV_FILENAME))
        return df.to_json()

    @task
    def transform(df: pd.DataFrame) -> pd.DataFrame:
        print("Going to transform the df..")
        df = pd.read_json(df)
        df['random_col'] = np.random.choice(range(1,100000), df.shape[0])
        print("The df was written and transformed.")
        return df.to_json()

    @task(outlets=Dataset(f"s3://{MINIO_ENDPOINT}/{BUCKET_NAME}/{CSV_FILENAME}"))
    def load(df: pd.DataFrame):
        df = pd.read_json(df)
        print("Going to load the dataframe.. It should trigger a consumer DAG according to data-aware scheduling of Airflow")
        client = Minio(MINIO_ENDPOINT, access_key=ACCESS_KEY, secret_key=SECRET_KEY, secure=False)
        csv = df.to_csv().encode('utf-8')
        client.put_object(
            BUCKET_NAME,
            CSV_FILENAME,
            data=BytesIO(csv),
            length=len(csv),
            content_type='application/csv'
        )

    df = extract()
    transformed_df = transform(df)
    load(transformed_df)

    
dag = dag_decorator()
```

`minio_consumer_dag.py`:
```python
from airflow import Dataset
from airflow.decorators import dag, task
from airflow.utils.dates import days_ago

MINIO_ENDPOINT = "host.docker.internal:9000"
ACCESS_KEY = "minio"
SECRET_KEY = "minio123"
BUCKET_NAME = "mybucket"
CSV_FILENAME = "wildfires.csv"

my_file = Dataset(f"s3://{MINIO_ENDPOINT}/{BUCKET_NAME}/{CSV_FILENAME}")

@dag(dag_id='minio_consumer', schedule=[my_file], start_date=days_ago(2), catchup=False, tags=["dataset"])
def dag_decorator():

    @task
    def print_msg():
        print("The wildfires.csv was changed.")
        
    print_msg()

dag = dag_decorator()
```

Run `astro dev start` again to setup minio service. 
 

6. Go to http://localhost:9001/buckets/ to see the uploaded csv into `mybucket` bucket in Minio. The credentials are `minio` and `minio123`. Turn on the DAGs and see the results, you would have to see something like this in the Airflow UI:
<img width="1052" alt="dataset_minio_screen" src="https://user-images.githubusercontent.com/14033798/204568740-30750245-29a6-4d27-b395-3b6cd3dcfd53.png">

7.   If you finished this tutorial, you can run `astro dev kill` to kill all the containers and other resources like networks and volumes.

Just to mention I took some ideas from @mrn-aglic that developed this [repo](https://github.com/mrn-aglic/examples). 

We are excited to share our knowledge from [Mutt Data](https://github.com/MuttData) in the Astronomer Registries (DAGs Registry is really interesting!).
